#ifndef PANELACTIONSCONST_H
#define PANELACTIONSCONST_H

namespace C_Actions
{
    enum C_Actions { MENUUP, MENUDOWN, MENULEFT, MENURIGHT, MENUVALIDATE, MENUCANCEL, UP, DOWN, LEFT, RIGHT, SWAP, RAISE, PAUSE };
}

#endif
